### ISSUE TITLE
BouncingJellyView中onSizeChanged方法中的contentHeight为0

### ISSUE THREAD

**Issue by xinnuo** [aohanyao/BouncingJelly#1]
BouncingJellyView类中onSizeChanged方法中获取可滚动的内容的高度contentHeight始终为0，判断方法没有用，当屏幕没有满屏时向上滑动，有明显的抖动现象。

**Comment by aohanyao** [comment]
能否贴上你的代码？

**Comment by xinnuo** [comment]
没有代码啊，只在布局里用包了一层LinearLayout布局。只要屏幕没充满不能滑动的情况下上滑就有这种情况。
protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        int contentHeight = this.getChildAt(0).getHeight();
        if(contentHeight > 0 && contentHeight <= ScreenUtils.getScreenHeight(this.getContext())) {
            this.mBouncingType = 1;
        }

    }
这个方法的contentHeight高度就是0，你把demo的数据减少几条就可以试

**Comment by aohanyao** [comment]
该问题已修复，可以查看一下最新版本。

**Comment by xinnuo** [comment]
ok
